name: Publish Docker
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: msosnov/got-helper
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy to Portainer
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}